GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Pajowturr's Epic Blog",
  "author": "Pajowturr Zwohrtenakaht",
  "url": "epicblog.com",
  "likes": 0
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog Post",
  "author": "Test Author",
  "url": "testblog.com",
  "likes": 5
}

###

GET http://localhost:3003/api/blogs/6895d49262070a9ec9584679

###

PUT http://localhost:3003/api/blogs/611111926207111119584679
Content-Type: application/json

{
  "title": "Updated Blog Title",
  "author": "Updated Author",
  "url": "updatedblog.com",
  "likes": 10
}

###

DELETE http://localhost:3003/api/blogs/611111926207111119584679
