GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Pajowturr's Epic Blog",
  "author": "Pajowturr Zwohrtenakaht",
  "url": "epicblog.com",
  "likes": 0
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "username",
  "name": "Joe Stone",
  "password": "askmd1jnmq09jsq"
}

###
GET http://localhost:3003/api/users